### PR TITLE
commit

### PR DESCRIPTION
**Pull request by odinthenerd**

### CODE REVIEW

**Comment by 0xc0170** [comment]
Can you provide useful commit message, if possible to split features to smaller chunks ? I was interested to see the new devices as I noticed SAM and MKE devices in here.

**Comment by CvRXX** [comment]
Yes Atmel! Going to try it tomorrow (will let Wouter know as well). Did you get my emails?

**Comment by odinthenerd** [comment]
Yes sorry about the giant glob. Whenever I change the generator script a whole lot of lines change. Every chip is supported for which there is a cmsis-svd file in @posborne s repo.

**Comment by odinthenerd** [comment]
@CvRXX looking forward to hear your experience. Got your mail, get back to you tomorrow.

**Pull request merged**
